name: "Aron-toso - Serve on AML Endpoint"
description: "Aron-toso Serve on AML Endpoint"
author: "aronchick"
inputs:
  METASTORE_CREDENTIALS:
    description: "Encoded URL, endpoint and credentials for logging into to a Gremlin server."
    required: true
  WORKFLOW_NODE_ID:
    description: "Workflow node for lookup."
    required: true
  STEP_NAME:
    description: "String that describes the name of this workflow step."
    required: true
  SCHEMAS_DIRECTORY:
    description: "Directory on disk that stores all schemas used to validate."
    required: true
    default: ".parameters/schemas"
  SCHEMAS_GIT_URL:
    description: "Git URL that contains the schemas for validation. Will be 'shallow' pulled during run."
    required: false
  PREVIOUS_STEP_NAME:
    description: "String that points to the previous step_name."
    required: false
  NEXT_STEP_NAME:
    description: "String that points to the next step_name."
    required: false
  INPUT_PARAMETERS_RAW:
    description: "String containing input parameters in yaml or json form. Will be validated against schema."
    required: false
  INPUT_PARAMETERS_BASE64:
    description: "String containing input parameters in yaml or json form encoded into URL Safe Base64. Will be validated against schema."
    required: false
  INPUT_PARAMETERS_NODE_ID:
    description: "String containing the Node ID on the Gremlin server of the input parameters to this step in the process. Will be validated against schema."
    required: false
  INPUT_PARAMETERS_FILE_PATH:
    description: "String containing the file path in the container of the input parameters of this step. Will be validated against schema."
    required: false
  EXECUTION_PARAMETERS_RAW:
    description: "String containing execution parameters in yaml or json form. Will be validated against schema."
    required: false
  EXECUTION_PARAMETERS_BASE64:
    description: "String containing input parameters in yaml or json form encoded into URL Safe Base64. Will be validated against schema."
    required: false
  EXECUTION_PARAMETERS_NODE_ID:
    description:  "String containing the Node ID on the Gremlin server of the execution parameters to this step in the process. Will be validated against schema."
    required: false
  EXECUTION_PARAMETERS_FILE_PATH:
    description: "String containing the file path in the container of the input parameters of this step. Will be validated against schema."
    required: false
output:
    output_base64_encoded:
      description: "Output of this step encoded into URL Safe Base64 text."
    input_node_id:
      description: "Node ID on the Gremlin server of the input."
    execution_node_id:
      description: "Node ID on the Gremlin server of the execution."
    output_node_id:
      description: "Node ID on the Gremlin server of the output."
    log_node_id:
      description: "Node ID on the Gremlin server of the logs."

branding:
  icon: "life-buoy"
  color: "purple"
runs: 
  using: 'docker'
  image: 'docker://mlspec/mlspeclib-action-samples-process-data:latest'
